"""empty message

Revision ID: 0f44013b420c
Revises: 3bfe83d33169
Create Date: 2019-06-08 23:30:42.325449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f44013b420c'
down_revision = '3bfe83d33169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_desc', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_product_product_desc'), 'product', ['product_desc'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_product_desc'), table_name='product')
    op.drop_column('product', 'product_desc')
    # ### end Alembic commands ###
