"""empty message

Revision ID: 35dd9e8ceccf
Revises: f0ace924cdad
Create Date: 2019-06-16 16:26:05.308656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35dd9e8ceccf'
down_revision = 'f0ace924cdad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'created_at')
    # ### end Alembic commands ###
