"""empty message

Revision ID: 38d173a9ec3a
Revises: 35dd9e8ceccf
Create Date: 2019-06-16 17:38:41.981743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d173a9ec3a'
down_revision = '35dd9e8ceccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sold', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_sold'), 'product', ['sold'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_sold'), table_name='product')
    op.drop_column('product', 'sold')
    # ### end Alembic commands ###
