"""empty message

Revision ID: 5449861b2c3c
Revises: ed198611eba1
Create Date: 2019-06-14 20:34:46.255019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import flask_appbuilder

# revision identifiers, used by Alembic.
revision = '5449861b2c3c'
down_revision = 'ed198611eba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product', ['id'])
    op.add_column('product_image', sa.Column('image', flask_appbuilder.models.mixins.ImageColumn(), nullable=True))
    op.drop_column('product_image', 'width')
    op.drop_column('product_image', 'original')
    op.drop_column('product_image', 'order_index')
    op.drop_column('product_image', 'created_at')
    op.drop_column('product_image', 'height')
    op.drop_column('product_image', 'mimetype')
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('product_image', sa.Column('mimetype', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('product_image', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_image', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('product_image', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_image', sa.Column('original', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('product_image', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('product_image', 'image')
    op.drop_constraint(None, 'product', type_='unique')
    # ### end Alembic commands ###
