"""empty message

Revision ID: 5c29832b8ca0
Revises: 87ec6cbc0433
Create Date: 2019-06-15 20:27:20.458864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c29832b8ca0'
down_revision = '87ec6cbc0433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('tag', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_product_discount'), 'product', ['discount'], unique=False)
    op.create_index(op.f('ix_product_tag'), 'product', ['tag'], unique=False)
    op.create_unique_constraint(None, 'product', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_index(op.f('ix_product_tag'), table_name='product')
    op.drop_index(op.f('ix_product_discount'), table_name='product')
    op.drop_column('product', 'tag')
    op.drop_column('product', 'discount')
    # ### end Alembic commands ###
