"""empty message

Revision ID: 87ec6cbc0433
Revises: 67bdf0fc8fb5
Create Date: 2019-06-14 21:44:41.967980

"""
from alembic import op
import sqlalchemy as sa
import flask_appbuilder

# revision identifiers, used by Alembic.
revision = '87ec6cbc0433'
down_revision = '67bdf0fc8fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('desc', sa.String(length=120), nullable=True),
    sa.Column('thumbnail', flask_appbuilder.models.mixins.ImageColumn(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_product_desc'), 'product', ['desc'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index(op.f('ix_product_price'), 'product', ['price'], unique=False)
    op.create_foreign_key(None, 'product_image', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_image', type_='foreignkey')
    op.drop_index(op.f('ix_product_price'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_desc'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
