"""empty message

Revision ID: 974b368ef507
Revises: 5c29832b8ca0
Create Date: 2019-06-16 11:45:10.131700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '974b368ef507'
down_revision = '5c29832b8ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discoun', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_discoun'), 'product', ['discoun'], unique=False)
    op.drop_index('ix_product_discount', table_name='product')
    op.drop_column('product', 'discount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('ix_product_discount', 'product', ['discount'], unique=False)
    op.drop_index(op.f('ix_product_discoun'), table_name='product')
    op.drop_column('product', 'discoun')
    # ### end Alembic commands ###
