"""empty message

Revision ID: bcf49fddaca4
Revises: 5449861b2c3c
Create Date: 2019-06-14 20:48:46.393064

"""
from alembic import op
import sqlalchemy as sa
import flask_appbuilder

# revision identifiers, used by Alembic.
revision = 'bcf49fddaca4'
down_revision = '5449861b2c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=True),
    sa.Column('product_desc', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_product_price'), 'product', ['price'], unique=False)
    op.create_index(op.f('ix_product_product_desc'), 'product', ['product_desc'], unique=False)
    op.create_index(op.f('ix_product_product_name'), 'product', ['product_name'], unique=False)
    op.create_table('product_image',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image', flask_appbuilder.models.mixins.ImageColumn(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image')
    op.drop_index(op.f('ix_product_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_product_desc'), table_name='product')
    op.drop_index(op.f('ix_product_price'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
