"""empty message

Revision ID: f0ace924cdad
Revises: 974b368ef507
Create Date: 2019-06-16 11:45:30.757127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ace924cdad'
down_revision = '974b368ef507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_discount'), 'product', ['discount'], unique=False)
    op.drop_index('ix_product_discoun', table_name='product')
    op.drop_column('product', 'discoun')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discoun', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_product_discoun', 'product', ['discoun'], unique=False)
    op.drop_index(op.f('ix_product_discount'), table_name='product')
    op.drop_column('product', 'discount')
    # ### end Alembic commands ###
